### ISSUE TITLE
Sound is wrong and has acceleration and cut

### ISSUE THREAD

**Issue by jamclucas** [kbeckmann/PicoDVI-N64#4]
sound  output is wrong and skips, the sound seems its acelerated.

**Comment by vcesne** [comment]
Same thing for me

**Comment by JackHammer04** [comment]
Audio issue for me as well. Some games echo and some it has an audio skip.

**Comment by Adess31** [comment]
me too :(

**Comment by antonytayron** [comment]
Guys, I had this same problem, in my case, I just changed the wires to wires if more quality, isolate all wires with a aluminiun and decrease wires size.

**Comment by spinalcode** [comment]
I don't think there is a way for the pico to know what the sample rate for the audio is, some games will be faster than others. As for the skipping or repeating, it is a small timer issue that perhaps could be solved bu double buffering the audio.

**Comment by krikris** [comment]
I'm interested in helping to solve this problem, because i have it too

**Comment by kbeckmann** [comment]
All, you may try the latest build. I have made significant improvements regarding this.

I've integrated the changes into the n64 branch. https://github.com/kbeckmann/PicoDVI-N64/commits/n64

**Comment by vcesne** [comment]
No problem anymore. It works like a charm. Thank you so much.

**Comment by antonytayron** [comment]
Thanks @kbeckmann, I tested with Turok 2 and the sound is perfect.
