### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by UnElectronicoMas** [kbeckmann/PicoDVI-N64#5]
Hello, thank you very much for the contribution to the community, it is hard to believe what a raspberry pico can do today. I have a question regarding the project, could it be used to capture the video signal from a neo geo mvs and output it via hdmi? thanks in advance.

**Comment by kbeckmann** [comment]
No, the code as it is written does only support N64 systems. However, the code could possibly be modified to support other systems, but it is not something I have looked into.
